name: CI

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cache Arduino CLI data
        uses: actions/cache@v6
        with:
          path: ~/.arduino15
          key: arduino-cli-${{ runner.os }}-${{ hashFiles('**/*.ino') }}
          restore-keys: |
            arduino-cli-${{ runner.os }}-

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ make

      - name: Install Catch2
        run: |
          sudo apt-get update
          sudo apt-get install -y catch2

      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          sudo mv bin/arduino-cli /usr/local/bin/

      - name: Run examples
        run: make examples

      - name: Run tests
        run: make test
